[package]
name = "bevy_dice"
version = "0.1.1"
authors = ["Sergei Surovtsev <ssurovsev@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Physics-based dice rolls for bevy"
keywords = ["bevy", "tabletop", "dice"]
repository = "https://github.com/stillonearth/bevy_rl"

[dependencies]
bevy = { version = "0.8.1" }
rand = "0.8.5"
bevy_rapier3d = { version = "0.17.0", features = [
    "simd-stable",
    "debug-render",
] }

[dev-dependencies]
bevy-debug-text-overlay = "3.0"
bevy-inspector-egui = { version = "0.13.0" }

[profile.dev]
opt-level = 3
