[package]
name = "bevy_dice"
version = "0.1.0"
authors = ["Sergei Surovtsev <ssurovsev@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.8.1" }
bevy-inspector-egui = { version = "0.13.0" }
bevy-debug-text-overlay = "3.0"
rand = "0.8.5"
bevy_rapier3d = { version = "0.17.0", features = [
    "simd-stable",
    "debug-render",
] }

[profile.dev]
opt-level = 3
