[package]
name = "bevy_dice"
version = "0.1.0"
authors = ["Sergei Surovtsev <ssurovsev@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.8.1" }
bevy-inspector-egui = { version = "0.13.0" }
heron = { version = "4.0.1", features = ["3d"] }
rand = "0.8.5"

[profile.dev]
opt-level = 3
